### ISSUE TITLE
Node-Errors.

### ISSUE THREAD

**Issue by lukasoppermann** [DavidAnson/check-pages#6]
Hey,

it generally works, but I get this error, any idea why?
```
[13:25:48] Error: 57 issues.
    at /Users/lukasoppermann/Code/formandsystem-cms/node_modules/check-pages/checkPages.js:426:13
    at next (/Users/lukasoppermann/Code/formandsystem-cms/node_modules/check-pages/checkPages.js:435:5)
    at /Users/lukasoppermann/Code/formandsystem-cms/node_modules/check-pages/checkPages.js:119:18
    at next (/Users/lukasoppermann/Code/formandsystem-cms/node_modules/check-pages/checkPages.js:435:5)
    at /Users/lukasoppermann/Code/formandsystem-cms/node_modules/check-pages/checkPages.js:119:18
    at next (/Users/lukasoppermann/Code/formandsystem-cms/node_modules/check-pages/checkPages.js:435:5)
    at /Users/lukasoppermann/Code/formandsystem-cms/node_modules/check-pages/checkPages.js:119:18
    at next (/Users/lukasoppermann/Code/formandsystem-cms/node_modules/check-pages/checkPages.js:435:5)
    at Request._callback (/Users/lukasoppermann/Code/formandsystem-cms/node_modules/check-pages/checkPages.js:314:9)
    at Request.self.callback (/Users/lukasoppermann/Code/formandsystem-cms/node_modules/request/request.js:200:22)
```

**Comment by DavidAnson** [comment]
If errors are detected, check-pages calls the `done` callback (third parameter of the export) with an `Error` instance that has more details. You can `console.log` that object for more information. Along the way, the `host` object (first parameter of the export) will have its `log` or `error` methods called with each issue. You can set `summary` of the `options` object (second parameter of the export) to `true` to include all errors in the error object as well.

Here's a simple, stand-alone example you can run via `node example.js` after `npm install check-pages`:

```js
var checkPages = require("check-pages");
checkPages(
  console,
  {
    pageUrls: ["http://google.com/"],
    checkLinks: true,
    checkXhtml: true
  },
  function(err, count) {
    if (err) {
      console.log("Error object: " + err);
    }
    console.log("Error count: " + count);
  }
);
```

**Comment by lukasoppermann** [comment]
Awesome, thanks.
